### ISSUE TITLE
missing optical flow results of videoflow

### ISSUE THREAD

**Issue by tb2-sy** [Zerg-Overmind/GaussianFlow#6]
Sorry to bother you again, in your paper you mentioned forward flow for supervision, but my videoflow results are missing the forward flow from 0001 to 0002, what should I do?
![cba6b8f7d7d953012aa634dc729a1c8c](https://github.com/Zerg-Overmind/GaussianFlow/assets/61854446/e07fa3d3-4cb6-4174-8c86-64dccbd429ae)

**Comment by tb2-sy** [comment]
Another question is the shape of predicted_flow_by_gs.sum(0) is [1080, 1920, 2], but videoflow optical_flow shape have 3 channels, how to use optical flow to supervise predicted flow? Looking forward to your reply.

**Comment by Zerg-Overmind** [comment]
Hi, the output of videoflow is [H,W,2], what you got here are the rgb images for visualization, not the raw optical flow. Also, you should carefully check the issues (for example [this](https://github.com/XiaoyuShi97/VideoFlow/issues/5)) and the readme file of videoflow because the way they calculating optical flow includes both forward and backward flow (if I remember correctly), you will need to pick out only forward ones for usage.
